### ISSUE TITLE
Museumsstück: 1977 PET Commodore 2001

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/windows-developer-unity#4]
https://en.wikipedia.org/wiki/Commodore_PET#PET_2001_series_/_2001-N_&_-B_series,_CBM_3000_series

Sollte geöffnet werden können, sodass man in das Innenleben schauen kann: https://en.wikipedia.org/wiki/Commodore_PET#/media/File:Commodore_PET_2001_with_lifted_top.jpg

@ChristianWeyer und @ValentinWeyer können hier sicherlich mit guten Bilder nachhelfen, falls öffentlich verfügbare Bilder zum Design des Assets nicht ausreichen sollten.

Siehe bspw. auch hier: https://3dwarehouse.sketchup.com/model/d2ea2570761a20e28ae63471e9a7921d/Commodore-PET-2001

![8BED4101-D662-4C5C-9224-DE0035158506](https://user-images.githubusercontent.com/740791/87931650-72e30680-ca8a-11ea-9160-a6c8e59ee766.png)

**Comment by ManuelRauber** [comment]
@ChristianWeyer @valentinweyer Könnt ihr uns gute Bilder vom Commodore liefern?

Am besten jede Seite einmal, auch innen drin. 

Danke :-)

**Comment by ChristianWeyer** [comment]
Reicht Samstag?

**Comment by ManuelRauber** [comment]
Na klar

--

Beste Grüße

Manuel Rauber

Sent from my iPhone

On 23. Jul 2020, at 16:42, Christian Weyer <notifications@github.com> wrote:

﻿

Reicht Samstag?

**Comment by ManuelRauber** [comment]
@lepsii Bilder :-)

![IMG_4121](https://user-images.githubusercontent.com/740791/88456524-a5bc3e80-ce7e-11ea-928e-713fa4507cf4.jpeg)
![IMG_4122](https://user-images.githubusercontent.com/740791/88456556-c7b5c100-ce7e-11ea-90ea-9ae50fc435b0.jpeg)
![IMG_4123](https://user-images.githubusercontent.com/740791/88456560-c8e6ee00-ce7e-11ea-810d-36bde4992d91.jpeg)
![IMG_4124](https://user-images.githubusercontent.com/740791/88456561-cab0b180-ce7e-11ea-9340-2689b3425cea.jpeg)
![IMG_4125](https://user-images.githubusercontent.com/740791/88456563-cb494800-ce7e-11ea-97f1-590c9e844fb1.jpeg)
![IMG_4126](https://user-images.githubusercontent.com/740791/88456565-cd130b80-ce7e-11ea-9ccb-f9e1b8fe1cac.jpeg)
![IMG_4127](https://user-images.githubusercontent.com/740791/88456566-ce443880-ce7e-11ea-965c-f84f241d34b0.jpeg)
![IMG_4128](https://user-images.githubusercontent.com/740791/88456567-cf756580-ce7e-11ea-8437-446014889cbb.jpeg)
![IMG_4129](https://user-images.githubusercontent.com/740791/88456568-d0a69280-ce7e-11ea-8454-58c045d80e23.jpeg)
![IMG_4130](https://user-images.githubusercontent.com/740791/88456571-d1d7bf80-ce7e-11ea-8fbc-679b7cd26137.jpeg)
![IMG_4131](https://user-images.githubusercontent.com/740791/88456572-d308ec80-ce7e-11ea-81cf-146496e9e903.jpeg)

**Comment by ChristianWeyer** [comment]
Nun endlich Bilder mit Maßen.

![Maße PET 2001-2](https://user-images.githubusercontent.com/888718/88788306-731f8800-d195-11ea-84e9-6acf3cd83f5b.jpg)
![Maße PET 2001-3](https://user-images.githubusercontent.com/888718/88788315-761a7880-d195-11ea-877f-7a307c6bde70.jpg)
![Maße PET 2001-4](https://user-images.githubusercontent.com/888718/88788318-76b30f00-d195-11ea-82d8-fa9a3e49bd00.jpg)
![Maße PET 2001-5](https://user-images.githubusercontent.com/888718/88788320-774ba580-d195-11ea-92fc-3678e5695078.jpg)
![Maße PET 2001-6](https://user-images.githubusercontent.com/888718/88788322-77e43c00-d195-11ea-8690-1aeef8ff0a4a.jpg)
![Maße PET 2001-7](https://user-images.githubusercontent.com/888718/88788326-787cd280-d195-11ea-9331-a07e07a573cf.jpg)
![Maße PET 2001-8](https://user-images.githubusercontent.com/888718/88788327-79156900-d195-11ea-8822-2f39f9049801.jpg)
![Maße PET 2001-9](https://user-images.githubusercontent.com/888718/88788329-79adff80-d195-11ea-86b5-c32a50f13a16.jpg)
![Tape Deck 1](https://user-images.githubusercontent.com/888718/88788458-a530ea00-d195-11ea-8963-3afacb4d6067.png)
![Tape Deck 2](https://user-images.githubusercontent.com/888718/88788560-c42f7c00-d195-11ea-95e7-c2b24f4af821.png)

@lepsii

**Comment by ManuelRauber** [comment]
Soweit als LowPoly-Modell mal done.
